version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.6-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "requirements_test.txt" }}
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install_requirements
      - save_cache:
          key: v1-deps-{{ checksum "requirements_test.txt" }}
          paths:
            - "venv"
      - run:
          name: Run Unit tests
          command: |
            . venv/bin/activate
            make pytest -- \
            --cov=. \
            --cov-config=.coveragerc \
            --cov-report=html \
            --junit-xml=./results/pytest_unit_report.xml \
            --alluredir=./allure_results/ \
            --ignore='./venv/'
            coveralls
      - store_test_results:
          path: ./results/

  test_browser:
    docker:
      - image: circleci/python:3.6.6-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "requirements_test.txt" }}
      - run:
          name: Install Allure CLI
          when: always
          command: |
            wget https://github.com/allure-framework/allure2/releases/download/2.13.1/allure-commandline-2.13.1.zip -O allure.zip
            unzip -q allure.zip
            find . -maxdepth 1 -type d -name "allure*" -exec mv {} allure \;
            rm allure.zip
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install_requirements
      - save_cache:
          key: v1-deps-{{ checksum "requirements_test.txt" }}
          paths:
            - "venv"
      - run:
          name: Run Browser tests
          command: |
            . venv/bin/activate
            make pytest_browser -- \
            --cov=. \
            --cov-config=.coveragerc \
            --cov-report=html \
            --junit-xml=./results/pytest_browser_report.xml \
            --alluredir=./allure_results/ \
            --ignore='./venv/'
      - store_test_results:
          path: ./results/
      - run:
          name: Generate Allure report
          when: always
          command: |
            export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
            export PATH=$PATH:$HOME/bin:$PATH:$JAVA_HOME/bin:./allure/bin
            allure generate --clean --output ./allure_report ./allure_results/
      - store_artifacts:
          path: ./allure_report/
          destination: allure_report

  test_load:
    working_directory: ~/greatcms
    docker:
      - image: circleci/python:3.6.6
    environment:
      NUM_CLIENTS: 20
      HATCH_RATE: 3
      RUN_TIME: 30s
    steps:
      - checkout
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            make install_requirements
      - run:
          name: Database and UI Setup
          command: |
            . venv/bin/activate
            make secrets
            ENV_FILES='test,dev' ./manage.py migrate
            ENV_FILES='test,dev' ./manage.py bootstrap_great
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            mkdir results
            make test_load
      - store_artifacts:
          path: ./results/
          destination: locust_results

  test_javascript:
    docker:
      - image: circleci/node:8.5.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run Javascript tests
          command: npm test

  flake8:
    docker:
    - image: circleci/python:3.6.6
    steps:
    - checkout
    - run:
        name: Run flake8
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install --quiet -r requirements_test.txt
          flake8

workflows:
  version: 2
  test_and_flake8:
    jobs:
      - test
      - test_browser
      - test_javascript
      - test_load
      - flake8
